IdealCareers/urls.py
from django.contrib import admin
from django.conf.urls import url, include


app_name = 'jobs'
urlpatterns = [
    url('admin/', admin.site.urls),
    url('jobs/', include(('jobs.urls', "jobs"), namespace='jobs')),

]

# urlpatterns += staticfiles_urlpatterns()
# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

jobs/urls.py
from django.urls import path

from . import views
from .views import (description_view, index_view, jobs_view, search_job_view,
                    subscribe_view)

urlpatterns = [
    path("index/", views.index_view, name='index'),
    path("detail/", views.search_job_view, name="detail"),
    path("description/<int:job_id>/", views.description_view),
    path("subscribe/", views.subscribe_view),
    path("jobs/", views.jobs_view),
]

jobs/models.py
from django.db import models


# Create your models here.


class UniqueIds(models.Model):
    class Meta:
        abstract = True

    #  public id to share with the the in url,
    #  Used for REST routes and public displays
    public_id = models.BigIntegerField(null=True, editable=False, unique=True)


class CommonInfo(models.Model):
    """
    This model is used for inheriting the common fields in other models requires the same fields.
    """

    class Meta:
        abstract = True

    name = models.CharField(max_length=50)
    email = models.EmailField(max_length=250)


class TechnicalSkills(UniqueIds):
    """
    This model is used to save the technical skills details.
    """

    name = models.CharField(max_length=50)
    description = models.CharField(max_length=500, null=True)

    class Meta:
        verbose_name = "Technical Skills"

    def __str__(self):
        return self.name


class Jobs(UniqueIds):
    """
    This model is used to save job details.
    """

    job_name = models.CharField(max_length=50)
    job_description = models.TextField(max_length=1000)
    tag = models.CharField(max_length=50, null=True, blank=True)
    max_exp = models.FloatField()
    min_exp = models.FloatField()
    active = models.BooleanField(verbose_name='active', default=True)
    start_date = models.DateField()
    end_date = models.DateField()
    skill = models.ForeignKey(
        TechnicalSkills, on_delete=models.CASCADE, related_name="technical_skill"
    )


class Apply(CommonInfo, UniqueIds):
    """
    This model is used to save the details of a person who applied for a job.
    """

    resume = models.FileField(upload_to="media", max_length=100)
    skill = models.ManyToManyField(TechnicalSkills)

    def __str__(self):
        return self.name


class Subscribers(CommonInfo, UniqueIds):
    """
    This model is used to save the details of a person for getting notifications.
    """

    location = models.CharField(max_length=50, blank=True)
    status = models.BooleanField(verbose_name='status', default=True)

    def __str__(self):
        return self.name

jobs/views.py
from django.shortcuts import render

from jobs.form import JobsForm, IndexForm

from .models import Jobs, Subscribers


# Create your views here.


def index_view(request):
    search = IndexForm()
    return render(request, "index.html", {'form': search})


def jobs_view(request):
    if request.method == "POST":
        form = JobsForm(request.POST)
        if form.is_valid():
            try:
                job = form.save(commit=False)
                job.save()
            except:
                pass
    else:
        form = JobsForm()
    return render(request, "jobs.html", {"form": form})


def search_job_view(request):
    if request.method == "POST":
        keywords = request.POST.get("keywords")
        location = request.POST.get("location")
        exp = request.POST.get("experience")
        # job = Jobs.objects.all()
        # breakpoint()
        # job_name = Jobs.objects.all().filter(job_name='job_name')
        context = {"keywords": keywords, "location": location, "exp": exp}
        return render(request, "details.html", {"context": context})


def description_view(request, job_id):
    job = Jobs.objects.get(job_id=job_id)
    descp = job.description
    desired_skills = job.desired_skills
    job_role = job.job_role
    job_functions = job.job_functions

    context1 = {
        "descp": descp,
        "job": job_id,
        "desired_skills": desired_skills,
        "job_role": job_role,
        "job_functions": job_functions,
    }

    return render(request, "description.html", {"context1": context1})


def subscribe_view(request):
    if request.method == "POST":
        if request.POST.get("email") and request.POST.get("name"):
            post = Subscribers()
            post.email = request.POST.get("email")
            post.name = request.POST.get("name")
            post.save()

            return render(request, "subscribe.html")

    else:
        return render(request, "subscribe.html")

jobs/templates/base.html
<link rel='stylesheet' href='/static/css/base.css' type='text/css'/>
{% block menu %}
<div class="header">
    <div class="header-right">
<nav>
<a>Home</a>
<a>My saved Jobs</a>
<a>Login</a>
</nav>
    </div>
</div>
{% endblock %}

jobs/templates/description.html
<!DOCTYPE html>
{% load custom_tags %}
{% jobs_obj as jobs %}
{% technology_obj as techno %}
{% role_obj as role %}


<html>

<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <!--    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" integrity="sha512-dTfge/zgoMYpP7QbHy4gWMEGsbsdZeCXz7irItjcC3sPUFtf0kuFbDz/ixG7ArTxmDjLXDmezHubeNikyKGVyQ==" crossorigin="anonymous">-->
    <link href="/static/css/description.css" rel="stylesheet">


    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <!--    <link href="/static/css/style.css" rel="stylesheet">-->

    <meta name="viewport" content="width=device-width, initial-scale=1.0">


</head>

<body>

<section>
    <div id="carouselExampleFade" class="carousel slide carousel-fade" data-ride="carousel">
        <div class="carousel-inner">
            <div class="carousel-item active">
                <img src="data:image/gif;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNkZWD8DgABFwD/1q0APQAAAABJRU5ErkJggg=="
                     class="d-block w-100" alt="...">
            </div>
            <div class="carousel-item">
                <img src="data:image/gif;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNkZWD8DgABFwD/1q0APQAAAABJRU5ErkJggg=="
                     class="d-block w-100" alt="...">
            </div>
            <div class="carousel-item">
                <img src="data:image/gif;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNkZWD8DgABFwD/1q0APQAAAABJRU5ErkJggg=="
                     class="d-block w-100" alt="...">
            </div>
            <!--https://upload.wikimedia.org/wikipedia/commons/8/8d/Yarra_Night_Panorama%2C_Melbourne_-_Feb_2005.jpg-->
        </div>
        <a class="carousel-control-prev" href="#carouselExampleFade" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleFade" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>
</section>
<div class="divcss">
    <h6>Job Description</h6>
    <p>{{context1.descp}}</p>
    <p>Job Function : {{context1.job_functions}}</p>
    <p>Role: {{context1.job_role}}</p>
    <p>Job ID : {{context1.job}}</p>
    <p>Desired Skills : {{context1.desired_skills}}</p>

</div>

<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script>

</body>

</html>

jobs/templates/details.html
{% extends "base.html" %}
{% block menu %}

<div class="header">
    <nav>
        <a>Home</a>
        <a>My saved Jobs</a>
        <a>Login</a>
    </nav>
</div>

    <div class="div">
        <tr>
        <td>{{context.keywords}}</td>
        <td>{{context.location}}</td>
        <td>{{context.exp}}</td>
        </tr>
    </div>
{% endblock %}

jobs/templates/index.html
<!DOCTYPE html>
{% extends "base.html" %}
{% block menu %}
<div class="header">
    <nav>
        <a>Home</a>
        <a>My saved Jobs</a>
        <a>Login</a>
    </nav>
</div>

<html lang="en">
<head>
    <meta charset="UTF-8">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link href="/static/css/style.css" rel="stylesheet">
</head>
<body>

<section>

    <div id="carouselExampleFade" class="carousel slide carousel-fade" data-ride="carousel">
        <div class="carousel-inner">
            <div class="carousel-item active">
                <img src="/static/images/images.jpeg" class="d-block w-100" alt="...">
            </div>
            <div class="carousel-item">
                <img src="/static/images/images (1).jpeg" class="d-block w-100" alt="...">
            </div>
            <div class="carousel-item">
                <img src="/static/images/job_images.jpeg" class="d-block w-100" alt="...">
            </div>
            <!--https://upload.wikimedia.org/wikipedia/commons/8/8d/Yarra_Night_Panorama%2C_Melbourne_-_Feb_2005.jpg-->
        </div>
        <a class="carousel-control-prev" href="#carouselExampleFade" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleFade" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>
</section>
<section class="search-sec">
    <div class="container">
        <form  method="post">
            {% csrf_token %}
            <div>
            {{ form.as_table }}
                <button type="submit" formaction="{% url 'jobs:detail' %}"
                >Search
                </button>
<!--            </div>-->
<!--            <div class="row">-->
<!--                <div class="col-lg-12">-->
<!--                    <div class="row">-->
<!--                        <div class="col-lg-3 col-md-3 col-sm-12 p-0">-->
<!--                            <input type="text" class="form-control search-slt" name="keywords" placeholder="Enter Keywords">-->
<!--                        </div>-->
<!--                        <div class="col-lg-3 col-md-3 col-sm-12 p-0">-->
<!--                            <input type="text" class="form-control search-slt" name="location" placeholder="Enter Location">-->
<!--                        </div>-->
<!--                        <div class="col-lg-3 col-md-3 col-sm-12 p-0">-->
<!--                            <select class="form-control search-slt" name="experience" placeholder="Experience" id="exampleFormControlSelect1">-->
<!--                                <option>Experience</option>-->
<!--                                <option>2-5 yrs</option>-->
<!--                                <option>5-14 yrs</option>-->
<!--                                <option>14-50 yrs</option>-->
<!--                            </select>-->
<!--                        </div>-->
<!--                        <div class="col-lg-3 col-md-3 col-sm-12 p-0">-->
<!--                            <button type="submit" formaction="{% url 'jobs:detail' %}"-->
<!--                                    >Search-->
<!--                            </button>-->
<!--                        </div>-->
<!--                    </div>-->
<!--                </div>-->
            </div>
        </form>
    </div>
    <button type="button" onclick="location.href='/jobs/subscribe/'" class="btn btn-primary">Subscribe</button>
</section>

<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script>
{% endblock %}
</body>
</html>

jobs/templates/jobs.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Jobs</title>
</head>
<body>
<form method="POST" class="post-form" enctype="multipart/form-data">
    {% csrf_token %}

    {{ form.as_p }}

<!--    <p>{{ form.non_field_errors }}</p>-->
<!--&lt;!&ndash;    <label>Remark : {{ form.remark }}</label>&ndash;&gt;-->
<!--    <label>job_name: {{form.job_name}}</label><br><br>-->
<!--    <label>job_description: {{ form.job_description }}</label><br><br>-->
<!--    <label>tag: {{ form.tag }}</label><br><br>-->
<!--    <label>min_exp: {{ form.min_exp }}</label><br><br>-->
<!--    <label>max_exp: {{ form.max_exp }}</label><br><br>-->
<!--    <label>active: {{ form.active }}</label><br><br>-->
<!--    <label>start_date: {{ form.start_date }}</label><br><br>-->
<!--    <label>end_date: {{ form.end_date }}</label><br><br>-->
<!--    <label>skill: {{ form.skill }}</label><br><br>-->

    <button type="submit"  class="save btn btn-default">Save</button>
</form>
</body>
</html>

jobs/templates/main.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link href="/static/css/style.css" rel="stylesheet">
</head>
<body>
<section>
    <div id="carouselExampleFade" class="carousel slide carousel-fade" data-ride="carousel">
        <div class="carousel-inner">
            <div class="carousel-item active">
                <img src="/static/images/images.jpeg" class="d-block w-100" alt="...">
            </div>
            <div class="carousel-item">
                <img src="/static/images/images (1).jpeg" class="d-block w-100" alt="...">
            </div>
            <div class="carousel-item">
                <img src="/static/images/job_images.jpeg" class="d-block w-100" alt="...">
            </div>
            <!--https://upload.wikimedia.org/wikipedia/commons/8/8d/Yarra_Night_Panorama%2C_Melbourne_-_Feb_2005.jpg-->
        </div>
        <a class="carousel-control-prev" href="#carouselExampleFade" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleFade" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>
</section>
<section class="search-sec">
    <div class="container">
        <form action="#" method="post" novalidate="novalidate">
            <div class="row">
                <div class="col-lg-12">
                    <div class="row">
                        <div class="col-lg-3 col-md-3 col-sm-12 p-0">
                            <input type="text" class="form-control search-slt" placeholder="Enter Pickup City">
                        </div>
                        <div class="col-lg-3 col-md-3 col-sm-12 p-0">
                            <input type="text" class="form-control search-slt" placeholder="Enter Drop City">
                        </div>
                        <div class="col-lg-3 col-md-3 col-sm-12 p-0">
                            <select class="form-control search-slt" id="exampleFormControlSelect1">
                                <option>Select Vehicle</option>
                                <option>Example one</option>
                                <option>Example one</option>
                                <option>Example one</option>
                                <option>Example one</option>
                                <option>Example one</option>
                                <option>Example one</option>
                            </select>
                        </div>
                        <div class="col-lg-3 col-md-3 col-sm-12 p-0">
                            <button type="button" class="btn btn-danger wrn-btn">Search</button>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
</section>
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

</body>
</html>

jobs/templates/subscribe.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <link rel='stylesheet' href='/static/css/subscribe.css' type='text/css'/>
</head>


<body onload='document.form1.text1.focus()'>
<div class="mail">
    <form action="" method="post">
        {% csrf_token %}
        <ul>
            <h2>Subscribe Now</h2>
            <input type="text" name="email" placeholder="Enter Email"><br><br>
            <input type="text" name="name" placeholder="Enter Name"><br><br>
            <input type="submit" name="submit" value="Subscribe" onclick="ValidateEmail(document.form1.text1)"/>
        </ul>
    </form>
</div>
<script src="/static/js/subscribe.js"></script>
</body>
</html>